name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    name: build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Install mdbook
        uses: taiki-e/install-action@mdbook
      - name: Install mdbook-linkcheck
        uses: taiki-e/install-action@mdbook-linkcheck
      - run: mdbook build
      - run: cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target
      - uses: rust-lang/simpleinfra/github-actions/static-websites@master
        with:
          deploy_dir: book/html
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: github.event_name == 'push' && github.ref == 'refs/heads/master' && github.repository_owner == 'rust-lang'
